#!/bin/bash
laptop_screen=eDP1
mirror_screen=$1
mode=$2
scale=$3
xrandr --output $laptop_screen --mode 1366x768 --scale 1x1 --output $mirror_screen --same-as $laptop_screen --mode $mode --scale ${scale}x${scale}

