#!/bin/bash
my_screen=eDP1; mode1=1366x768
width=`echo $2 | cut -d'x' -f1`
scale=`awk "BEGIN{print 1366/${width}}"`
echo $width $scale
# xrandr --output $my_screen --mode $mode1 --scale 1x1 --output $1 --same-as $my_screen --mode $2 --scale ${scale}x${scale}

